### ISSUE TITLE
SQLite one to one displayed as optional one to many

### ISSUE THREAD

**Issue by drsjb80** [wise-coders/dbschema#105]
1. Please check DbSchema Help / Output logs for errors.
No errors, but the line
07:06:37 REVERSE ENGINEERED 4 TABLES FROM Sqlite.
might be indicative.

3. Please include the DbSchema version, operating system and used database
9.3.0 and SQLite3.

4. The steps to reproduce this issue
I'm using Rails and SQLite3. Here's the statement in the schema

CREATE TABLE IF NOT EXISTS "people" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "phone_id" integer NOT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL, CONSTRAINT "fk_rails_15f655d702"
FOREIGN KEY ("phone_id")
  REFERENCES "phones" ("id")
);

I was expecting the relation between people and phones to have the two lines (one and mandatory) but I'm seeing multiple and optional (see attached image). I'm sure I'm missing something, can someone point me in the right direction? Thanks!

![Untitled](https://github.com/wise-coders/dbschema/assets/2523112/820381f6-6075-42fd-8bdd-958581d7190a)

**Comment by wise-coders** [comment]
Phone_id can be null as there could be no record in people pointing to a given phone. This can be enforced only using triggers.
And there could be multiple peoples using the same phoneid, as the phone_id is not indexed unique.

We had some improvements in the notation after we introduced the logical design. We had to use the same conversions for both, logical and physical.

**Comment by drsjb80** [comment]
Okay, I get that phone_id isn't unique here, but when I do 

sqlite> INSERT INTO people VALUES(3, 'Bob Smith', NULL, '2022-09-18 15:45:42.252176','2022-09-18 15:45:42.252176');
Error: NOT NULL constraint failed: people.phone_id

which seems to indicate non-optional. Rails does say:

The Active Record way claims that intelligence belongs in your models, not in the database. As such, features such as triggers or constraints, which push some of that intelligence back into the database, are not recommended. (https://edgeguides.rubyonrails.org/active_record_migrations.html#foreign-keys)

so certain aspects of the DB are being enforced by Rails, but NOT NULL in people for phone_id does seem to be enforced by SQLite3, making it non-optional, but I might be using the wrong term here.

Thanks for the response above! I'll continue to figure this all out. Love your program!

**Comment by Psyclo1** [comment]
The relationship between Phones and People can be read two ways.  First, from Phones to People, it is Zero-to-Many, since I can define Phones that aren't associated with People.  Technically, the People table could be empty, and I could have a thousand Phones records, perfectly fine.  From People to Phones is a mandatory 1:1.  If I create a record in People, since the column is mandatory, it *must* have a value, and that value *must* be a valid Phones ID.  You can change the FK notation to Information Engineering (without arrows), as shown in the attached picture, and it will show the line on the Phones side of the relationship indicating the mandatory 1:1.
![LayoutFKNotations](https://github.com/wise-coders/dbschema/assets/81329093/021b78a9-ea8f-4028-b2b5-92bea9a4a5ec)
Also note that the line is solid, which in DbSchema indicates the mandatory FK column.  If you changed phone_id to nullable, the line would become dashed, and the Phones end would become a circle.

Hope this helps.
Mike Nicewarner

**Comment by drb80** [comment]
It helps a lot! I'll continue to work through all of this. And I agree with flipping the relationship, I'm not sure why I started with it the other way around. Thanks much!
