### ISSUE TITLE
Shortcut capture activated by Alt+Tab key combination, still remains after switching to another application

### ISSUE THREAD

**Issue by lucacestola** [wise-coders/dbschema#4]
DbSchema version: 8.2.7 build 200130 (OpenJRE 13 runtime)
O.S. version: Windows 10 Pro build 1909
Database: Sql Server Enterprise 10.50.6220.0

**Description**
While interacting with the Create Table form, using Alt+Tab key combination leaves the keyboard shortcut active also when the user come back to DbSchema, so that typing leads to unexpected shortcut activation.

**Repro Steps**
Having at least another application opened on desktop, beyond DbSchema
Open a layout diagram
Select create Table Command
Select a schema and click Ok button (the new table model form opens)
Stay on the "Columns" tab active
Press Alt+Tab in order to switch to another opened application
Press Alt+Tab again in order to switch back to DbSchema
Press the "A" key (the shortcut for adding a column is executed)

**Comment by wise-coders** [comment]
This issue has to be fixed in JavaFx. We have created an issue for them:
https://github.com/javafxports/openjdk-jfx/issues/622

Pressing Alt will activate button mnemonic, so typing the corresponding button letter will activate the button:
![image](https://user-images.githubusercontent.com/60284259/73969589-fc0ee280-491b-11ea-98c0-83a8e9d34c3f.png)

This works fine, but pressing Alt+tab has two KeyPress events: KeyPress.Alt -> intercepted by JavaFx will trigger the mnemonic, KeyPress.Tab -> intercepted by Windows, will move the application in background. So when returning back to the application with the second Alt-Tab will find the dialog in Mnemonic Active state.
